[language.elm]
filetypes = ["elm"]
roots = ["elm.json"]
command = "elm-language-server"
args = ["--stdio"]

[language.elm.initialization_options]
elmPath = "elm"
elmFormatPath = "elm-format"
elmTestPath = "elm-test"
elmAnalyseTrigger = "change"
