eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(elm) %{
  lsp-enable
  lsp-auto-hover-enable
  map -docstring "language-server mode" global user l ': enter-user-mode lsp<ret>'
  set global formatcmd "elm-format --stdin --yes --elm-version 0.19"
  set global lsp_auto_highlight_references true
  set global lsp_hover_anchor true
}

map global normal <a-q> ': delete-buffer<ret>'
map global normal <c-s> 'Z%2@z: write<ret>'
map global normal <c-q> ': quit<ret>'
map global normal <a-n> ': buffer-next<ret>'
map global normal <a-p> ': buffer-previous<ret>'
map global insert <a-k> <esc>
map -docstring "format buffer" global user f ': format<ret>'

set global ui_options ncurses_assistant=none
set global tabstop 2
set global indentwidth 2

hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}
